import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { ListingCard } from "@/components/listing-card";
import { useAuth } from "@/hooks/use-auth";
import { listenMyListings } from "@/lib/marketplace";
import { colors } from "@/lib/ui";
import type { Listing } from "@/types/marketplace";

export default function AccountScreen() {
  const router = useRouter(); const { user, isAdmin, logout, refreshAdminClaim } = useAuth(); const [items, setItems] = useState<Listing[]>([]); const [loading, setLoading] = useState(false);
  useEffect(() => { if (!user) { setItems([]); return; } setLoading(true); return listenMyListings(user.uid, (list) => { setItems(list); setLoading(false); }); }, [user]);
  if (!user) return <ScreenContainer className="px-4"><View style={styles.center}><Text style={styles.title}>حسابي</Text><Text style={styles.muted}>سجّل الدخول لإدارة إعلاناتك وعروضك.</Text><Pressable onPress={() => router.push("/auth" as never)} style={styles.primary}><Text style={styles.primaryText}>تسجيل الدخول</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer className="px-4"><ScrollView contentContainerStyle={styles.content}><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{(user.displayName || user.email || "A").slice(0, 1).toUpperCase()}</Text></View><View style={styles.profileText}><Text style={styles.title}>{user.displayName || "مستخدم avendOc"}</Text><Text style={styles.muted}>{user.email}</Text></View></View><View style={styles.actions}><Pressable onPress={() => router.push("/(tabs)/create" as never)} style={styles.primary}><Text style={styles.primaryText}>+ نشر إعلان</Text></Pressable>{isAdmin && <Pressable onPress={async () => { await refreshAdminClaim(); router.push("/(tabs)/admin" as never); }} style={styles.admin}><Text style={styles.adminText}>لوحة الأدمين</Text></Pressable>}<Pressable onPress={() => { Alert.alert("تسجيل الخروج", "هل تريد تسجيل الخروج؟", [{ text: "إلغاء", style: "cancel" }, { text: "خروج", style: "destructive", onPress: logout }]); }} style={styles.logout}><Text style={styles.logoutText}>تسجيل الخروج</Text></Pressable></View><Text style={styles.section}>إعلاناتي ({items.length})</Text>{loading ? <ActivityIndicator color={colors.primary} /> : items.length === 0 ? <Text style={styles.muted}>لم تنشر أي إعلان بعد.</Text> : items.map((item) => <ListingCard key={item.id} listing={item} onPress={() => router.push((`/listing/${item.id}`) as never)} />)}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 30 }, profile: { flexDirection: "row-reverse", alignItems: "center", gap: 12, paddingVertical: 10 }, profileText: { flex: 1, gap: 4 }, avatar: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, avatarText: { color: "white", fontSize: 24, fontWeight: "900" }, title: { color: colors.text, fontSize: 24, fontWeight: "900", textAlign: "right" }, muted: { color: colors.muted, textAlign: "right" }, actions: { gap: 9 }, primary: { backgroundColor: colors.primary, padding: 13, borderRadius: 12, alignItems: "center" }, primaryText: { color: "white", fontWeight: "900" }, admin: { backgroundColor: "#FFF3BF", padding: 13, borderRadius: 12, alignItems: "center" }, adminText: { color: "#8A6100", fontWeight: "900" }, logout: { borderColor: "#F3C2C2", borderWidth: 1, padding: 12, borderRadius: 12, alignItems: "center" }, logoutText: { color: colors.danger, fontWeight: "800" }, section: { color: colors.text, fontSize: 19, fontWeight: "900", textAlign: "right", marginTop: 6 }, center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 } });
