import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { listenPendingListings, listenUsers, setListingStatus, setUserBlocked } from "@/lib/marketplace";
import { colors, formatDzd } from "@/lib/ui";
import type { AdminUser, Listing } from "@/types/marketplace";

export default function AdminScreen() {
  const { isAdmin } = useAuth(); const [listings, setListings] = useState<Listing[]>([]); const [users, setUsers] = useState<AdminUser[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!isAdmin) return; const u1 = listenPendingListings(setListings, (e) => setError(e.message)); const u2 = listenUsers(setUsers, (e) => setError(e.message)); setLoading(false); return () => { u1(); u2(); }; }, [isAdmin]);
  if (!isAdmin) return <ScreenContainer className="px-4"><View style={styles.center}><Text style={styles.denied}>الوصول مرفوض</Text><Text style={styles.muted}>هذه الشاشة متاحة للمستخدم الذي يحمل Custom Claim admin=true فقط.</Text></View></ScreenContainer>;
  async function changeStatus(item: Listing, status: Listing["status"]) { try { await setListingStatus(item.id, status, status === "REJECTED" ? "تم الرفض من لوحة الإدارة" : ""); } catch (e) { Alert.alert("تعذر التحديث", e instanceof Error ? e.message : "تحقق من قواعد Firestore."); } }
  async function toggleUser(item: AdminUser) { try { await setUserBlocked(item.id, !item.isBlocked); } catch (e) { Alert.alert("تعذر تحديث المستخدم", e instanceof Error ? e.message : "حاول مرة أخرى."); } }
  return <ScreenContainer className="px-4"><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>لوحة الأدمين</Text><Text style={styles.muted}>مراجعة الإعلانات وإدارة الحسابات — {listings.length} إعلانًا قيد الانتظار</Text>{error ? <Text style={styles.error}>{error}</Text> : null}{loading ? <ActivityIndicator color={colors.primary} /> : null}<Text style={styles.section}>إعلانات بانتظار المراجعة</Text>{listings.length === 0 ? <Text style={styles.muted}>لا توجد إعلانات جديدة.</Text> : listings.map((item) => <View key={item.id} style={styles.card}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.meta}>{item.sellerName} · {item.wilayaNameAr}</Text><Text style={styles.price}>{formatDzd(item.priceDzd)}</Text><Text style={styles.description}>{item.description}</Text><View style={styles.actions}><Pressable onPress={() => changeStatus(item, "REJECTED")} style={styles.reject}><Text style={styles.rejectText}>رفض</Text></Pressable><Pressable onPress={() => changeStatus(item, "PUBLISHED")} style={styles.accept}><Text style={styles.acceptText}>نشر الإعلان</Text></Pressable></View></View>)}<Text style={styles.section}>المستخدمون ({users.length})</Text>{users.slice(0, 50).map((item) => <View key={item.id} style={styles.userRow}><View style={styles.userText}><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.meta}>{item.phone || item.email || item.id}</Text></View><Pressable onPress={() => toggleUser(item)} style={[styles.block, item.isBlocked && styles.unblock]}><Text style={styles.blockText}>{item.isBlocked ? "رفع الحظر" : "حظر"}</Text></Pressable></View>)}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 13, paddingBottom: 30 }, title: { color: colors.text, fontSize: 26, fontWeight: "900", textAlign: "right" }, section: { color: colors.text, fontSize: 18, fontWeight: "900", textAlign: "right", marginTop: 8 }, muted: { color: colors.muted, textAlign: "right", lineHeight: 20 }, error: { color: colors.danger, backgroundColor: "#FFF0F0", padding: 11, borderRadius: 10, textAlign: "right" }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 16, padding: 15, gap: 8 }, cardTitle: { color: colors.text, fontWeight: "900", fontSize: 15, textAlign: "right" }, meta: { color: colors.muted, fontSize: 12, textAlign: "right" }, price: { color: colors.primary, fontWeight: "900", fontSize: 16, textAlign: "right" }, description: { color: colors.text, textAlign: "right", lineHeight: 20 }, actions: { flexDirection: "row-reverse", gap: 8, marginTop: 4 }, accept: { flex: 1, backgroundColor: colors.primary, borderRadius: 10, alignItems: "center", padding: 11 }, acceptText: { color: "white", fontWeight: "900" }, reject: { flex: 1, borderColor: "#F3C2C2", borderWidth: 1, borderRadius: 10, alignItems: "center", padding: 11 }, rejectText: { color: colors.danger, fontWeight: "800" }, userRow: { flexDirection: "row-reverse", alignItems: "center", gap: 10, backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 13, padding: 11 }, userText: { flex: 1, gap: 3 }, block: { backgroundColor: "#FFE3E3", paddingHorizontal: 11, paddingVertical: 8, borderRadius: 9 }, unblock: { backgroundColor: "#E8F5EF" }, blockText: { color: colors.danger, fontWeight: "800" }, center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 10 }, denied: { color: colors.danger, fontSize: 22, fontWeight: "900" } });
