import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { FormField } from "@/components/form-field";
import { useAuth } from "@/hooks/use-auth";
import { createListing } from "@/lib/marketplace";
import { colors } from "@/lib/ui";
import { CATEGORIES, CONDITIONS, DELIVERY_OPTIONS } from "@/types/marketplace";

export default function CreateScreen() {
  const router = useRouter();
  const { user } = useAuth();
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [price, setPrice] = useState(""); const [category, setCategory] = useState("vehicles"); const [condition, setCondition] = useState("LIKE_NEW"); const [wilaya, setWilaya] = useState("16"); const [commune, setCommune] = useState(""); const [phone, setPhone] = useState(""); const [delivery, setDelivery] = useState("ALL_69_WILAYAS"); const [negotiable, setNegotiable] = useState(true); const [busy, setBusy] = useState(false);
  async function submit() { if (!user) { router.push("/auth" as never); return; } if (!title.trim() || !description.trim() || Number(price) <= 0 || !phone.trim()) { Alert.alert("بيانات ناقصة", "أدخل العنوان والوصف والسعر ورقم الهاتف."); return; } setBusy(true); try { await createListing({ title: title.trim(), description: description.trim(), priceDzd: Number(price), isNegotiable: negotiable, category, wilayaCode: wilaya || "16", wilayaNameAr: "الجزائر", wilayaNameFr: "Alger", commune: commune.trim() || "الجزائر", condition, sellerId: user.uid, sellerName: user.displayName || user.email || "بائع", sellerPhone: phone.trim(), images: [], deliveryOption: delivery, paymentReference: "", paymentDate: "" }); Alert.alert("تم استلام الإعلان", "سيظهر بعد مراجعة إيصال الدفع من الإدارة."); setTitle(""); setDescription(""); setPrice(""); router.push("/(tabs)/account" as never); } catch (error) { Alert.alert("تعذر نشر الإعلان", error instanceof Error ? error.message : "حاول مرة أخرى."); } finally { setBusy(false); } }
  return <ScreenContainer className="px-4"><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>نشر إعلان جديد</Text><Text style={styles.subtitle}>كل إعلان يمر بمراجعة الإدارة قبل ظهوره في السوق.</Text><FormField label="عنوان الإعلان" value={title} onChangeText={setTitle} placeholder="مثال: هاتف مستعمل بحالة جيدة" /><FormField label="الوصف" value={description} onChangeText={setDescription} placeholder="اذكر التفاصيل والحالة..." multiline numberOfLines={4} style={styles.textarea} /><FormField label="السعر بالدينار" value={price} onChangeText={setPrice} keyboardType="number-pad" placeholder="30000" /><FormField label="رقم الهاتف" value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="0550000000" /><FormField label="رمز الولاية" value={wilaya} onChangeText={setWilaya} keyboardType="number-pad" placeholder="16" /><FormField label="البلدية" value={commune} onChangeText={setCommune} placeholder="الجزائر" /><Text style={styles.label}>التصنيف</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.options}>{CATEGORIES.map((item) => <Pressable key={item.id} onPress={() => setCategory(item.id)} style={[styles.option, category === item.id && styles.optionActive]}><Text style={[styles.optionText, category === item.id && styles.optionTextActive]}>{item.ar}</Text></Pressable>)}</ScrollView><Text style={styles.label}>الحالة</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.options}>{CONDITIONS.map((item) => <Pressable key={item.id} onPress={() => setCondition(item.id)} style={[styles.option, condition === item.id && styles.optionActive]}><Text style={[styles.optionText, condition === item.id && styles.optionTextActive]}>{item.ar}</Text></Pressable>)}</ScrollView><Text style={styles.label}>طريقة التسليم</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.options}>{DELIVERY_OPTIONS.map((item) => <Pressable key={item.id} onPress={() => setDelivery(item.id)} style={[styles.option, delivery === item.id && styles.optionActive]}><Text style={[styles.optionText, delivery === item.id && styles.optionTextActive]}>{item.ar}</Text></Pressable>)}</ScrollView><View style={styles.switchRow}><Text style={styles.label}>السعر قابل للتفاوض</Text><Switch value={negotiable} onValueChange={setNegotiable} trackColor={{ true: colors.primary }} /></View><Pressable disabled={busy} onPress={submit} style={styles.primary}><Text style={styles.primaryText}>{busy ? "جارٍ الإرسال..." : "إرسال الإعلان للمراجعة"}</Text></Pressable></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 13, paddingBottom: 30 }, title: { color: colors.text, fontSize: 26, fontWeight: "900", textAlign: "right" }, subtitle: { color: colors.muted, textAlign: "right", lineHeight: 20 }, textarea: { minHeight: 108, textAlignVertical: "top", paddingTop: 12 }, label: { color: colors.text, fontWeight: "800", textAlign: "right" }, options: { gap: 8, paddingVertical: 2 }, option: { borderWidth: 1, borderColor: colors.border, borderRadius: 16, paddingHorizontal: 12, paddingVertical: 9, backgroundColor: colors.surface }, optionActive: { backgroundColor: colors.primary, borderColor: colors.primary }, optionText: { color: colors.text, fontSize: 12 }, optionTextActive: { color: "white", fontWeight: "800" }, switchRow: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", paddingVertical: 8 }, primary: { minHeight: 52, alignItems: "center", justifyContent: "center", backgroundColor: colors.primary, borderRadius: 13, marginTop: 8 }, primaryText: { color: "white", fontWeight: "900", fontSize: 15 } });
