import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { listenOffers, updateOffer } from "@/lib/marketplace";
import { colors, formatDzd } from "@/lib/ui";
import type { Offer } from "@/types/marketplace";

export default function OffersScreen() {
  const router = useRouter(); const { user } = useAuth(); const [offers, setOffers] = useState<Offer[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!user) { setLoading(false); return; } return listenOffers(user.uid, (items) => { setOffers(items); setLoading(false); }); }, [user]);
  async function respond(offer: Offer, status: Offer["status"]) { try { await updateOffer(offer.id, status); } catch (error) { Alert.alert("تعذر تحديث العرض", error instanceof Error ? error.message : "حاول مرة أخرى."); } }
  if (!user) return <ScreenContainer className="px-4"><View style={styles.center}><Text style={styles.title}>العروض والمساومة</Text><Text style={styles.muted}>سجّل الدخول لمتابعة عروضك.</Text><Pressable onPress={() => router.push("/auth" as never)} style={styles.primary}><Text style={styles.primaryText}>تسجيل الدخول</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer className="px-4"><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>العروض والمساومة</Text>{loading ? <ActivityIndicator color={colors.primary} /> : offers.length === 0 ? <View style={styles.center}><Text style={styles.muted}>لا توجد عروض بعد.</Text></View> : offers.map((offer) => <View key={offer.id} style={styles.card}><Text style={styles.cardTitle}>{offer.listingTitle}</Text><Text style={styles.meta}>{offer.buyerId === user.uid ? "عرضك للبائع" : `عرض من ${offer.buyerName || "مشتري"}`}</Text><View style={styles.row}><Text style={styles.price}>{formatDzd(offer.proposedPriceDzd)}</Text><Text style={[styles.status, offer.status === "ACCEPTED" && styles.accepted]}>{offer.status}</Text></View>{offer.message ? <Text style={styles.message}>{offer.message}</Text> : null}{offer.sellerId === user.uid && offer.status === "PENDING" && <View style={styles.actions}><Pressable onPress={() => respond(offer, "REJECTED")} style={styles.reject}><Text style={styles.rejectText}>رفض</Text></Pressable><Pressable onPress={() => respond(offer, "ACCEPTED")} style={styles.accept}><Text style={styles.acceptText}>قبول العرض</Text></Pressable></View>}</View>)}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 30 }, title: { color: colors.text, fontSize: 25, fontWeight: "900", textAlign: "right", marginBottom: 4 }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 18, padding: 16, gap: 9 }, cardTitle: { color: colors.text, fontSize: 17, fontWeight: "900", textAlign: "right" }, meta: { color: colors.muted, textAlign: "right", fontSize: 12 }, row: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, price: { color: colors.primary, fontSize: 18, fontWeight: "900" }, status: { color: colors.accent, fontWeight: "800", fontSize: 12 }, accepted: { color: colors.success }, message: { color: colors.text, textAlign: "right" }, actions: { flexDirection: "row-reverse", gap: 8, marginTop: 4 }, accept: { flex: 1, backgroundColor: colors.primary, alignItems: "center", padding: 11, borderRadius: 10 }, acceptText: { color: "white", fontWeight: "800" }, reject: { flex: 1, borderColor: "#F3C2C2", borderWidth: 1, alignItems: "center", padding: 11, borderRadius: 10 }, rejectText: { color: colors.danger, fontWeight: "800" }, primary: { backgroundColor: colors.primary, padding: 14, borderRadius: 12, marginTop: 12, paddingHorizontal: 25 }, primaryText: { color: "white", fontWeight: "800", textAlign: "center" }, center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 }, muted: { color: colors.muted, textAlign: "center" } });
