import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { onAuthStateChanged, signInWithEmailAndPassword, signOut, User } from 'firebase/auth';
import { collection, doc, onSnapshot, orderBy, query, updateDoc, where } from 'firebase/firestore';
import { auth, db } from './src/firebase';

type Listing = { id: string; title: string; description?: string; priceDzd?: number; sellerName?: string; sellerPhone?: string; wilayaNameAr?: string; status?: string; rejectionReason?: string };

function Login() { const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const submit=async()=>{if(!email.trim()||!password)return Alert.alert('تنبيه','أدخل البريد وكلمة المرور.');setBusy(true);try{const credential=await signInWithEmailAndPassword(auth,email.trim(),password);const token=await credential.user.getIdTokenResult(true);if(token.claims.admin!==true){await signOut(auth);Alert.alert('مرفوض','هذا الحساب لا يملك صلاحية admin.');}}catch(e:any){Alert.alert('تعذر الدخول',e?.message??'تحقق من بياناتك.')}finally{setBusy(false)}};return <SafeAreaView style={styles.safe}><View style={styles.card}><Text style={styles.brand}>AvendOc Admin</Text><Text style={styles.subtitle}>لوحة إدارة الإعلانات والمستخدمين</Text><Text style={styles.heading}>دخول الأدمن</Text><TextInput style={styles.input} placeholder="البريد الإلكتروني" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail}/><TextInput style={styles.input} placeholder="كلمة المرور" secureTextEntry value={password} onChangeText={setPassword}/><Pressable style={styles.primary} onPress={submit} disabled={busy}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>تسجيل الدخول</Text>}</Pressable><Text style={styles.hint}>يجب أن يكون للحساب Custom Claim باسم admin في Firebase.</Text></View></SafeAreaView> }

function Dashboard({user}:{user:User}) { const [items,setItems]=useState<Listing[]>([]); const [error,setError]=useState(''); useEffect(()=>{const q=query(collection(db,'listings'),where('status','==','PAYMENT_PENDING'),orderBy('createdAt','desc'));return onSnapshot(q,snap=>{setError('');setItems(snap.docs.map(d=>({id:d.id,...d.data()} as Listing)))},e=>setError(e.message??'تعذر تحميل الإعلانات.'))},[]);const change=async(item:Listing,status:'PUBLISHED'|'REJECTED')=>{try{const rejectionReason=status==='REJECTED'?'تم الرفض من الإدارة':'';await updateDoc(doc(db,'listings',item.id),{status,rejectionReason,updatedAt:new Date()});Alert.alert('تم','تم تحديث حالة الإعلان.')}catch(e:any){Alert.alert('فشل التحديث',e?.message??'تحقق من الصلاحيات.')}};return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><View style={styles.header}><View><Text style={styles.brand}>لوحة الأدمن</Text><Text style={styles.subtitle}>{user.email}</Text></View><Pressable onPress={()=>signOut(auth)}><Text style={styles.link}>خروج</Text></Pressable></View><Text style={styles.heading}>في انتظار المصادقة ({items.length})</Text>{error?<Text style={styles.error}>{error}</Text>:null}{items.length===0?<Text style={styles.empty}>لا توجد إعلانات بانتظار المراجعة.</Text>:items.map(item=><View style={styles.listing} key={item.id}><Text style={styles.listingTitle}>{item.title}</Text><Text>{item.description}</Text><Text style={styles.price}>{item.priceDzd?.toLocaleString('fr-FR')} دج</Text><Text style={styles.muted}>البائع: {item.sellerName||'غير معروف'} · {item.sellerPhone||''}</Text><Text style={styles.muted}>{item.wilayaNameAr||'الجزائر'}</Text><View style={styles.actions}><Pressable style={styles.approve} onPress={()=>change(item,'PUBLISHED')}><Text style={styles.primaryText}>موافقة ونشر</Text></Pressable><Pressable style={styles.reject} onPress={()=>change(item,'REJECTED')}><Text style={styles.rejectText}>رفض</Text></Pressable></View></View>)}</ScrollView></SafeAreaView> }

export default function App(){const[user,setUser]=useState<User|null>(null);const[ready,setReady]=useState(false);const[admin,setAdmin]=useState(false);useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);if(u){try{const token=await u.getIdTokenResult(true);setAdmin(token.claims.admin===true);if(token.claims.admin!==true)await signOut(auth)}catch{await signOut(auth)}}else setAdmin(false);setReady(true)}),[]);if(!ready)return <View style={styles.center}><ActivityIndicator color="#087f5b"/></View>;return user&&admin?<Dashboard user={user}/>:<Login/>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f7f6'},center:{flex:1,alignItems:'center',justifyContent:'center'},container:{padding:20,paddingBottom:40},card:{margin:20,marginTop:90,padding:24,borderRadius:20,backgroundColor:'#fff',elevation:3},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:25},brand:{fontSize:26,fontWeight:'800',color:'#087f5b'},subtitle:{color:'#667085',marginBottom:16},heading:{fontSize:21,fontWeight:'800',color:'#172b24',marginTop:18,marginBottom:12},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d7e0dc',borderRadius:10,padding:13,marginBottom:10,textAlign:'right'},primary:{backgroundColor:'#087f5b',padding:14,borderRadius:10,alignItems:'center',marginTop:5},primaryText:{color:'#fff',fontWeight:'800'},link:{color:'#087f5b',fontWeight:'700',padding:14},hint:{fontSize:12,color:'#667085',marginTop:16,lineHeight:18},empty:{textAlign:'center',color:'#667085',marginTop:30},error:{color:'#b42318',backgroundColor:'#fee4e2',padding:12,borderRadius:10},listing:{backgroundColor:'#fff',borderRadius:14,padding:15,marginBottom:12,elevation:1},listingTitle:{fontSize:17,fontWeight:'800',marginBottom:6},price:{fontSize:17,fontWeight:'800',color:'#087f5b',marginTop:8},muted:{fontSize:12,color:'#667085',marginTop:7},actions:{flexDirection:'row',gap:10,marginTop:14},approve:{flex:1,backgroundColor:'#087f5b',padding:12,borderRadius:9,alignItems:'center'},reject:{padding:12,borderRadius:9,borderWidth:1,borderColor:'#b42318',alignItems:'center'},rejectText:{color:'#b42318',fontWeight:'800'} });
