import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signOut, User } from 'firebase/auth';
import { addDoc, collection, onSnapshot, orderBy, query, serverTimestamp, where } from 'firebase/firestore';
import { auth, db } from './src/firebase';

type Listing = { id: string; title: string; description?: string; priceDzd?: number; wilayaNameAr?: string };

function AuthScreen() {
  const [register, setRegister] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async () => { if (!email.trim() || password.length < 6) return Alert.alert('تنبيه', 'أدخل بريدًا صحيحًا وكلمة مرور من 6 أحرف على الأقل.'); setBusy(true); try { if (register) await createUserWithEmailAndPassword(auth, email.trim(), password); else await signInWithEmailAndPassword(auth, email.trim(), password); } catch (e: any) { Alert.alert('تعذر الدخول', e?.message ?? 'تحقق من بياناتك.'); } finally { setBusy(false); } };
  return <SafeAreaView style={styles.safe}><View style={styles.authCard}><Text style={styles.brand}>AvendOc</Text><Text style={styles.subtitle}>سوق المستعمل الجزائري</Text><Text style={styles.heading}>{register ? 'إنشاء حساب' : 'تسجيل الدخول'}</Text><TextInput style={styles.input} placeholder="البريد الإلكتروني" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail}/><TextInput style={styles.input} placeholder="كلمة المرور" secureTextEntry value={password} onChangeText={setPassword}/><Pressable style={styles.primary} onPress={submit} disabled={busy}>{busy ? <ActivityIndicator color="#fff"/> : <Text style={styles.primaryText}>{register ? 'إنشاء الحساب' : 'دخول'}</Text>}</Pressable><Pressable onPress={() => setRegister(!register)}><Text style={styles.link}>{register ? 'لدي حساب بالفعل' : 'إنشاء حساب جديد'}</Text></Pressable></View></SafeAreaView>;
}

function UserHome({ user }: { user: User }) {
  const [listings, setListings] = useState<Listing[]>([]); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [price, setPrice] = useState('');
  useEffect(() => { const q = query(collection(db, 'listings'), where('status', '==', 'PUBLISHED'), orderBy('createdAt', 'desc')); return onSnapshot(q, snap => setListings(snap.docs.map(d => ({ id: d.id, ...d.data() } as Listing))), () => setListings([])); }, []);
  const publish = async () => { if (!title.trim()) return Alert.alert('تنبيه', 'اكتب عنوان الإعلان.'); try { await addDoc(collection(db, 'listings'), { title: title.trim(), description: description.trim(), priceDzd: Number(price) || 0, sellerId: user.uid, sellerName: user.email ?? '', sellerPhone: '', status: 'PAYMENT_PENDING', category: 'OTHER', wilayaCode: '16', wilayaNameAr: 'الجزائر', images: [], isNegotiable: true, viewsCount: 0, offersCount: 0, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); setTitle(''); setDescription(''); setPrice(''); Alert.alert('تم الإرسال', 'في انتظار مصادقة الإدارة ولن يظهر الإعلان في السوق حتى الموافقة.'); } catch (e: any) { Alert.alert('تعذر الإرسال', e?.message ?? 'تحقق من اتصال Firebase.'); } };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><View style={styles.header}><View><Text style={styles.brand}>AvendOc</Text><Text style={styles.subtitle}>{user.email}</Text></View><Pressable onPress={() => signOut(auth)}><Text style={styles.link}>خروج</Text></Pressable></View><Text style={styles.heading}>السوق</Text>{listings.map(item => <View style={styles.listing} key={item.id}><Text style={styles.listingTitle}>{item.title}</Text><Text>{item.description}</Text><Text style={styles.price}>{item.priceDzd?.toLocaleString('fr-FR')} دج</Text><Text style={styles.muted}>{item.wilayaNameAr ?? 'الجزائر'} · منشور بعد موافقة الإدارة</Text></View>)}<Text style={styles.heading}>نشر إعلان</Text><TextInput style={styles.input} placeholder="عنوان الإعلان" value={title} onChangeText={setTitle}/><TextInput style={[styles.input, styles.multiline]} placeholder="الوصف" multiline value={description} onChangeText={setDescription}/><TextInput style={styles.input} placeholder="السعر بالدج" keyboardType="number-pad" value={price} onChangeText={setPrice}/><Pressable style={styles.primary} onPress={publish}><Text style={styles.primaryText}>إرسال للمراقبة</Text></Pressable></ScrollView></SafeAreaView>;
}

export default function App() { const [user, setUser] = useState<User | null>(null); const [ready, setReady] = useState(false); useEffect(() => onAuthStateChanged(auth, u => { setUser(u); setReady(true); }), []); if (!ready) return <View style={styles.center}><ActivityIndicator color="#087f5b"/></View>; return user ? <UserHome user={user}/> : <AuthScreen/>; }

const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:'#f5f7f6'}, center:{flex:1,alignItems:'center',justifyContent:'center'}, container:{padding:20,paddingBottom:40}, authCard:{margin:20,marginTop:90,padding:24,borderRadius:20,backgroundColor:'#fff',elevation:3}, header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:25}, brand:{fontSize:26,fontWeight:'800',color:'#087f5b'}, subtitle:{color:'#667085',marginBottom:16}, heading:{fontSize:21,fontWeight:'800',color:'#172b24',marginTop:18,marginBottom:12}, input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d7e0dc',borderRadius:10,padding:13,marginBottom:10,textAlign:'right'}, multiline:{minHeight:90,textAlignVertical:'top'}, primary:{backgroundColor:'#087f5b',padding:14,borderRadius:10,alignItems:'center',marginTop:5}, primaryText:{color:'#fff',fontWeight:'800'}, link:{color:'#087f5b',fontWeight:'700',textAlign:'center',padding:14}, listing:{backgroundColor:'#fff',borderRadius:14,padding:15,marginBottom:12,elevation:1}, listingTitle:{fontSize:17,fontWeight:'800',marginBottom:6}, price:{fontSize:17,fontWeight:'800',color:'#087f5b',marginTop:8}, muted:{fontSize:12,color:'#667085',marginTop:7} });
